name: "Setup LCOV"
author: "KAnggara <KAnggara75@gmail.com>"
description: "Composite GitHub Action to setup LCOV."

inputs:
  coverage-files:
    default: "coverage/lcov.info"
    required: false
    description: "The coverage files to scan. For example, `coverage/lcov.info`"
  out-dir:
    default: "coverage"
    required: false
    description: " Write HTML output to OUTDIR. For example, `coverage`"
  working-dir:
    description: "The working directory containing the source files referenced in the LCOV files. Optional. Default: `./`"

runs:
  using: "composite"
  steps:
    - name: Install LCOV
      run: $GITHUB_ACTION_PATH/setup.sh
      shell: bash

    - name: Generate Html File from lcov
      shell: bash
      env:
        WD: ${{ inputs.working-dir }}
        OUTDIR: ${{ inputs.out-dir }}
        COVERAGE_FILE: ${{ inputs.coverage-files }}
      run: |
        mkdir $GITHUB_WORKSPACE/$OUTDIR
        cd $WD
        genhtml $COVERAGE_FILE --rc branch_coverage=1 -o $GITHUB_WORKSPACE/$OUTDIR

    - name: Check LCOV genhtml Version
      shell: bash
      env:
        OUTDIR: ${{ inputs.out-dir }}
      run: |
        ls -la
        pwd
        ls -la $GITHUB_WORKSPACE/$OUTDIR
        cd $GITHUB_WORKSPACE/$OUTDIR
        pwd
        ls -la

    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest
  
    - name: Build binary
      shell: bash
      run: |
        cd $GITHUB_ACTION_PATH
        bun build $GITHUB_ACTION_PATH/src/main.ts --compile --outfile=main

    - name: tes bun Bin
      shell: bash
      run: $GITHUB_ACTION_PATH/main

branding:
  icon: "play-circle"
  color: "blue"
