name: "Maven Build"
description: "Build Maven Project tp jar packege and upload artifact"

inputs:
  application-properties:
    description: "Value of application properties from secrets"
    required: false
  path:
    description: "Path of Maven Project, default ./"
    required: false
  java-version:
    description: 'The Java version to set up. Takes a whole or semver Java version. See examples of supported syntax in README file'
  distribution:
    description: 'Java distribution. See the list of supported distributions in README file'
    required: true

runs:
  using: "composite"
  steps:      
    - name: Using Java ${{ inputs.java-version }} ${{ inputs.distribution }}
      uses: actions/setup-java@v4.7.0
      with:
        java-version: ${{ inputs.java-version }}
        distribution: ${{ inputs.distribution }}

    - name: Generate application properties and Build
      shell: bash
      env:
        WORK_DIR: ${{ inputs.path }}
        APPLICATION_PROPERTIES: ${{ inputs.application-properties }}
      run: $GITHUB_ACTION_PATH/mavenbuild.sh

    - uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event.repository.name }}
        path: mavenbuild
