name: "Docker Image Build"

description: "Greet someone"

inputs:
  path:
    description: "Path of Maven Project, default ./"
    required: false

outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}

runs:
  using: "composite"
  steps:
    - name: Log in to the Container registry
      uses: docker/login-action@v3.3.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5.6.1
      with:
        images: ghcr.io/${{ github.repository }}

    - name: Build and push Docker image
      id: push
      uses: docker/build-push-action@v6.13.0
      with:
        context: ${{ inputs.path }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Generate artifact attestation
      uses: actions/attest-build-provenance@v2.2.0
      with:
        subject-name: ghcr.io/${{ github.repository }}
        subject-digest: ${{ steps.push.outputs.digest }}
        push-to-registry: true
