on:
  push:
    branches:
      - main
    paths:
      - "dockerbuild/**"
      - "dockerfile"
      - "dockerFile"
      - "DockerFile"
      - "Dockerfile"

jobs:
  dockerbuild:
    runs-on: ubuntu-latest
    name: Build Docker Image
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: KAnggara/DevOps/dockerbuild@HEAD
        with:
          path: test/bun
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
