on: [push]

jobs:
  dockerbuild:
    runs-on: ubuntu-latest
    name: Build Docker Image
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: KAnggara/DevOps/dockerbuild@HEAD
        with:
          path: ./bun
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
